### ISSUE TITLE
Display NO doesn't work

### ISSUE THREAD

**Issue by mobluse** [MrYsLab/s2m#9]
`Display NO` doesn't work. In the console I get:
```
Exception happened during processing of request from ('127.0.0.1', 51842)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "c:\python27\lib\site-packages\s2m\s2m_http_server.py", line 80, in do_GET
    self.process_command(cmd_list)
  File "c:\python27\lib\site-packages\s2m\s2m_http_server.py", line 127, in process_command
    resp = self.s2m.handle_display_image(cmd_list[1])
  File "c:\python27\lib\site-packages\s2m\s2m.py", line 327, in handle_display_image
    if data[2] == '_':
IndexError: string index out of range
----------------------------------------

```

I use this system:
```
s2m version 1.10  Copyright(C) 2017 Alan Yorinks  All rights reserved.

Python Version 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
Autodetecting serial port. Please wait...
Using COM Port:com3

s2mb Version: s2mb.py Version 1.05 05 December 2017
```

**Comment by MrYsLab** [comment]
Thanks. I have a fix and it will be included in v1.11.
